### ISSUE TITLE
Поля обработчиков Правила конвертации группы не заменяются на поля HTML

### ISSUE THREAD

**Issue by petypen** [GenVP/TipsInCD3#10]
Спасибо вам за супер инструмент!

В форме _Правило конвертации группы_ поля обработчиков не заменяются на поля HTML

Конвертация данных, редакция 3.1 (3.1.1.4)
1С:Предприятие 8.3 (8.3.18.1520)
КД3_КонтекстнаяПодсказка 1.2.1

Разрабатывается конвертация в формате XML (в формате КД21) В _Администрирование - Используемый функционал_ установлена галочка _Использовать формат XML_

Как проверить
1. Создать правило конвертации объектов
2. В ПКО на закладке _Правила конвертации_ свойств нажать кнопку _Создать группу_
3. На вновь созданной группе нажать правую кнопку мыши и выбрать Изменить или нажать клавишу F2, после чего откроется форма Правила конвертации группы
Код обработчиков черный.

![2021-07-30 17-15-05 Конвертация данных, редакция 3 1](https://user-images.githubusercontent.com/6500075/127666755-cb48ebe3-821f-4b45-a069-95005d9c68f0.png)
![2021-07-30 17-18-05 Правило конвертации группы  --  КонтактнаяИнформация (Правила конвертации свойств)](https://user-images.githubusercontent.com/6500075/127666771-df78d6e1-3d75-48ab-a1ff-98a57d4f22dc.png)

**Comment by GenVP** [comment]
Спасибо!
