### ISSUE TITLE
Адаптация под вышедшею КД3.1

### ISSUE THREAD

**Issue by VolAll** [GenVP/TipsInCD3#3]
вышла новая версия КД3 https://dl03.1c.ru/content/Conversion/3_1_1_3/news.htm

Адаптация под вышедшею КД 3.1.1.3 ?

у себя поставил, немного подкорректировал вроде работает.

**Comment by GenVP** [comment]
@VolAll посмотрю в ближайшие дни

**Comment by GenVP** [comment]
Обновлено в 1.1.1
